### PR TITLE
Removed profile name

### PR DESCRIPTION
**Pull request by Thingyman-DEV**
I think this should fix it, but I'm no expert, so tell me if I forgot to remove something.

### CODE REVIEW

**Comment by Thingyman-DEV** [comment]
@R4356th Is this ok?

**Comment by R4356th** [comment]
Yes, @Thingyman-DEV. This should work. Thank you for this!

**Comment by Thingyman-DEV** [comment]
@R4356th May I be added as a contributor please?

**Comment by R4356th** [comment]
Adding!

**Pull request merged**
