### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by HPD1155**
You did the error wrong. I fixed it.

### CODE REVIEW

**Comment by R4356th** [comment]
Hello, thank you very much for deciding to contribute to Glitchy Scratch! Could you please explain what you mean by "wrong"? It is intentionally like that.

**Comment by HPD1155** [comment]
The, "server worker registered" and "server worker denied", line 12

**Comment by R4356th** [comment]
Yes, I get that. What I do not get is what you mean by "wrong"? Is there any context here?

**Comment by HPD1155** [comment]
Wrong means like, you messed up the log message.

**Comment by R4356th** [comment]
I really do not see what is wrong with the message as it really is just a choice of words if there is no specific background. Please feel free to contribute in other ways. Thank you. 😃

**Pull request closed without merging**
