### PR TITLE
Huge Prettier Changes

### LINKED ISSUE #15: Prettifying index.html
#13 prettified all JS and CSS files but index.html was left out. Prettifying this is not very important but the prettified version is easy-to-read. Back when I was updating the news and other stuff in that file, it was very hard to edit it. The prettified code can be seen [here](https://glitch.com/edit/#!/glitchy-scratch?path=index.html%3A5019%3A52). // cc @Glitchy-Scratch/contributors

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
This now automatically prettifies all files! It uses GH Actions to do this. Every commit starts formatting.
Resolves #15

### CODE REVIEW

**Comment by GrahamSH-LLK** [comment]
Resolves #15

**Comment by GrahamSH-LLK** [comment]
//cc @R4356th

**Review by R4356th — APPROVED** [review]
Cool! Please let me know when it is ready for merging.

**Comment by GrahamSH-LLK** [comment]
It i!

**Comment by R4356th** [comment]
Thank you again!

**Comment by GrahamSH-LLK** [comment]
> Thank you again!

You're welcome! Honestly, I stole it from @ScratchAddons

**Pull request merged**
