### PR TITLE
Revert "The word mess up script breaks itself, this pull request fixes that."

### PR DESCRIPTION
**Pull request by R4356th**
Reverts Glitchy-Scratch/glitchy-scratch.github.io#3

### CODE REVIEW

**Comment by R4356th** [comment]
@BoomerScratch , that has created other unwanted bugs. I have to revert that. Sorry.

**Comment by BoomerScratch** [comment]
What bugs?

**Comment by R4356th** [comment]
> What bugs?
> EDIT: oh i see now. But that makes it better right? Or should i make a new pull request with fixes?

If possible and you have interest, you can of course make a pull request with fixes. And that is always appreciated. I love people helping me out with coding.

**Comment by BoomerScratch** [comment]
> > What bugs?
> > EDIT: oh i see now. But that makes it better right? Or should i make a new pull request with fixes?
> 
> If possible and you have interest, you can of course make a pull request with fixes. And that is always appreciated. I love people helping me out with coding.

I have resetted my fork with git, so this repository is even with the fork. [I have found the problem, i found out some other things](https://scratch.mit.edu/discuss/post/3968481/), and i think it is best to keep it like it is currently.

**Pull request merged**
